---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  client_rb:
    ssl_verify_mode: ":verify_none"

platforms:
  - name: centos-6.7-vbox
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: virtualbox
  - name: centos-6.7-vmware
    driver:
      box: bento/centos-6.7
      box_url: bento/centos-6.7
      provider: vmware_fusion
  - name: windows-2012r2

suites:
  - name: default
    excludes:
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::kitchen]

#  NOTE: Once serverspec can autodetect the backend, this won't be needed
  - name: windefault
    includes:      
      - windows-2012r2
    run_list:
      - recipe[doi_ssl_filtering]

  - name: java-oracle
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::kitchen]
      - recipe[java]
      - recipe[doi_ssl_filtering::java]
    data_bags_path: './test/integration/default/data_bags/'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'
    attributes: {
      "java" : {
          "install_flavor" : "oracle",
          "jdk_version" : "8",
          "oracle" : {
               "accept_oracle_download_terms" : true
          }
      }
    }

  - name: java-openjdk
    run_list:
      - recipe[doi_ssl_filtering]
      - recipe[doi_ssl_filtering::kitchen]
      - recipe[java]
      - recipe[doi_ssl_filtering::java]
    data_bags_path: './test/integration/default/data_bags/'
    encrypted_data_bag_secret_key_path: './test/integration/default/encrypted_data_bag_secret'

